name: challenge-01

on: push

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: print date 
      run: date '+%Y-%m-%d'
  job2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: print date 
      run: Get-Date
  job3:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: print date 
      run: date '+%Y-%m-%d'
    
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
    - uses: actions/checkout@v1
    - name: print date 
      run: date '+%Y-%m-%d'